server:
  port: 8888

spring:
  application:
    name: eureka-server
  security:
    user:
      name: tyron
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#eureka.client.registerWithEureka 表示是否将自己注册到Eureka Server， 默认为true。 由于当前应用就是Eureka Server， 因此设为 false；
#eureka.client.fetchRegistry 表示是否从Eureka Server获取注册信息，默认为true。 如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false。




